"""initial migration

Revision ID: 29ac4ee412ee
Revises: None
Create Date: 2016-03-07 17:20:28.801414

"""

# revision identifiers, used by Alembic.
revision = '29ac4ee412ee'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
